### ISSUE TITLE
8.0.11 ZeebeClientStarterAutoConfiguration required a bean of type 'io.camunda.zeebe.client.api.JsonMapper' that could not be found.

### ISSUE THREAD

**Issue by zxiaozhou** [camunda-community-hub/spring-zeebe#240] opened 2022-10-12 06:51 UTC
update to 8.0.11 not start
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method builder in io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration required a bean of type 'io.camunda.zeebe.client.api.JsonMapper' that could not be found.


Action:

Consider defining a bean of type 'io.camunda.zeebe.client.api.JsonMapper' in your configuration.

```

**Comment by berndruecker** [comment] 2022-10-12 06:57
Thanks for reporting @zxiaozhou - actually this bean should be optional, let me double check why this is not the case and come back. You could keep running 8.0.9 for the time being

**Comment by berndruecker** [comment] 2022-10-12 07:08
This is pretty wired. The bean is missing here: https://github.com/camunda-community-hub/spring-zeebe/blob/8.0.11/client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java#L35
But actually created here: https://github.com/camunda-community-hub/spring-zeebe/blob/8.0.11/client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java#L70

@bulivlad: Do you have any idea why this is failing? 

@zxiaozhou: I can't reproduce the problem with some of my local Spring Boot apps, they all run fine with 8.0.11 - any chance you share some part of your code that I could see how the application is wired together?

**Comment by berndruecker** [comment] 2022-10-12 12:26
I agree - really wired. Waiting for @zxiaozhou now - and decided that this will not block the 8.1.0 release.

**Comment by zxiaozhou** [comment] 2022-10-14 03:21
@berndruecker I get an error when I add the spring-cloud-starter-stream-rabbit dependency
the  demo
[spring-zeebe-demo.zip](https://github.com/camunda-community-hub/spring-zeebe/files/9782199/spring-zeebe-demo.zip)

**Comment by zxiaozhou** [comment] 2022-10-14 03:22
@berndruecker I get an error when I add the spring-cloud-starter-stream-rabbit dependency
the  demo
[spring-zeebe-demo.zip](https://github.com/camunda-community-hub/spring-zeebe/files/9782199/spring-zeebe-demo.zip)

**Comment by zxiaozhou** [comment] 2022-10-14 03:24
log info
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zeebeClientLifecycle' defined in io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration: Unsatisfied dependency expressed through method 'zeebeClientLifecycle' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zeebeClientObjectFactory' defined in io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration: Unsatisfied dependency expressed through method 'zeebeClientObjectFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'builder' defined in class path resource [io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.zeebe.client.ZeebeClientBuilder]: Factory method 'builder' threw exception; nested exception is java.lang.IllegalStateException: @Bean method ZeebeClientStarterAutoConfiguration.jsonMapper called as bean reference for type [io.camunda.zeebe.client.api.JsonMapper] but overridden by non-compatible bean instance of type [org.springframework.cloud.function.json.JacksonMapper]. Overriding bean of same name declared in: class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration$JsonMapperConfiguration.class]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.example.springzeebe.SpringZeebeApplication.main(SpringZeebeApplication.java:14) ~[main/:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zeebeClientObjectFactory' defined in io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration: Unsatisfied dependency expressed through method 'zeebeClientObjectFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'builder' defined in class path resource [io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.zeebe.client.ZeebeClientBuilder]: Factory method 'builder' threw exception; nested exception is java.lang.IllegalStateException: @Bean method ZeebeClientStarterAutoConfiguration.jsonMapper called as bean reference for type [io.camunda.zeebe.client.api.JsonMapper] but overridden by non-compatible bean instance of type [org.springframework.cloud.function.json.JacksonMapper]. Overriding bean of same name declared in: class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration$JsonMapperConfiguration.class]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.23.jar:5.3.23]
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'builder' defined in class path resource [io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.zeebe.client.ZeebeClientBuilder]: Factory method 'builder' threw exception; nested exception is java.lang.IllegalStateException: @Bean method ZeebeClientStarterAutoConfiguration.jsonMapper called as bean reference for type [io.camunda.zeebe.client.api.JsonMapper] but overridden by non-compatible bean instance of type [org.springframework.cloud.function.json.JacksonMapper]. Overriding bean of same name declared in: class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration$JsonMapperConfiguration.class]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.23.jar:5.3.23]
	... 33 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.zeebe.client.ZeebeClientBuilder]: Factory method 'builder' threw exception; nested exception is java.lang.IllegalStateException: @Bean method ZeebeClientStarterAutoConfiguration.jsonMapper called as bean reference for type [io.camunda.zeebe.client.api.JsonMapper] but overridden by non-compatible bean instance of type [org.springframework.cloud.function.json.JacksonMapper]. Overriding bean of same name declared in: class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration$JsonMapperConfiguration.class]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.23.jar:5.3.23]
	... 47 common frames omitted
Caused by: java.lang.IllegalStateException: @Bean method ZeebeClientStarterAutoConfiguration.jsonMapper called as bean reference for type [io.camunda.zeebe.client.api.JsonMapper] but overridden by non-compatible bean instance of type [org.springframework.cloud.function.json.JacksonMapper]. Overriding bean of same name declared in: class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration$JsonMapperConfiguration.class]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:386) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:334) ~[spring-context-5.3.23.jar:5.3.23]
	at io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration$$EnhancerBySpringCGLIB$$1da79eac.jsonMapper(<generated>) ~[spring-zeebe-starter-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration.builder(ZeebeClientStarterAutoConfiguration.java:52) ~[spring-zeebe-starter-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration$$EnhancerBySpringCGLIB$$1da79eac.CGLIB$builder$2(<generated>) ~[spring-zeebe-starter-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration$$EnhancerBySpringCGLIB$$1da79eac$$FastClassBySpringCGLIB$$b8a96f98.invoke(<generated>) ~[spring-zeebe-starter-8.1.0.jar:8.1.0]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.23.jar:5.3.23]
	at io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration$$EnhancerBySpringCGLIB$$1da79eac.builder(<generated>) ~[spring-zeebe-starter-8.1.0.jar:8.1.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	... 48 common frames omitted
```

**Comment by berndruecker** [comment] 2022-10-14 04:39
Thanks for those details @zxiaozhou - very helpful! I can't look at it today but try to come back to it next week. @bulivlad WDYT?

**Comment by bulivlad** [comment] 2022-10-14 09:11
thanks for the details @zxiaozhou. I don't think I can get the time to look into it until tomorrow. in the mean time if this is a blocking issue you can work it around by manually overriding the default bean in your application 
```
@Bean
public JsonMapper zeebeJsonMapper() {
    return new ZeebeObjectMapper();
}
```

**Comment by berndruecker** [comment] 2022-10-14 18:24
Should be fixed by https://github.com/camunda-community-hub/spring-zeebe/pull/243 - please reopen if not!

**Closed by berndruecker** 2022-10-14 18:24 UTC
