### ISSUE TITLE
8.1.8 No serializer found for class io.camunda.zeebe.client.impl.ZeebeObjectMapper

### ISSUE THREAD

**Issue by zxiaozhou** [camunda-community-hub/spring-zeebe#281] opened 2022-12-02 00:35 UTC
1. error info
```
No serializer found for class io.camunda.zeebe.client.impl.ZeebeObjectMapper and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.camunda.zeebe.client.impl.ZeebeClientImpl["configuration"]->io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl["jsonMapper"])
```
2. error log
```
2022-12-02 08:34:35.648 ERROR [,,] 56766 --- [   scheduling-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.converter.MessageConversionException: Could not write JSON: No serializer found for class io.camunda.zeebe.client.impl.ZeebeObjectMapper and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.camunda.zeebe.client.impl.ZeebeClientImpl["configuration"]->io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl["jsonMapper"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.camunda.zeebe.client.impl.ZeebeObjectMapper and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.camunda.zeebe.client.impl.ZeebeClientImpl["configuration"]->io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl["jsonMapper"])
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertToInternal(MappingJackson2MessageConverter.java:274)
	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertToInternal(ApplicationJsonMessageMarshallingConverter.java:71)
	at org.springframework.messaging.converter.AbstractMessageConverter.toMessage(AbstractMessageConverter.java:201)
	at org.springframework.messaging.converter.AbstractMessageConverter.toMessage(AbstractMessageConverter.java:191)
	at org.springframework.cloud.function.context.config.SmartCompositeMessageConverter.toMessage(SmartCompositeMessageConverter.java:156)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertOutputIfNecessary(SimpleFunctionRegistry.java:1208)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:592)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.get(SimpleFunctionRegistry.java:600)
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.get(PartitionAwareFunctionWrapper.java:95)
	at org.springframework.integration.dsl.IntegrationFlows$1.doReceive(IntegrationFlows.java:174)
	at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:142)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:212)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:444)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:413)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:348)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:341)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.camunda.zeebe.client.impl.ZeebeObjectMapper and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.camunda.zeebe.client.impl.ZeebeClientImpl["configuration"]->io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl["jsonMapper"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3160)
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertToInternal(MappingJackson2MessageConverter.java:256)
	... 26 more
```

3. demo
[spring-zeebe-demo.zip](https://github.com/camunda-community-hub/spring-zeebe/files/10137172/spring-zeebe-demo.zip)

4. run env
```
zeebe: 8.1.4
jdk: 11.0.16
spring zeebe :8.1.8
```
5. I found that the error occurred when the cloud was upgraded to 2021.0.5. The specific cause has not been found yet(If the demo above is changed to 2021.0.4, it will return to normal)

**Comment by lzgabel** [comment] 2022-12-02 04:27
This issue is a duplicate of https://github.com/camunda/zeebe/issues/10797, we need to backport [#camunda/zeebe/10944](https://github.com/camunda/zeebe/pull/10944) to `stable/8.1` and `stable/8.0`

**Closed by lzgabel** 2022-12-02 04:27 UTC

**Comment by lzgabel** [comment] 2022-12-02 05:04
👋 Hi @zxiaozhou. There is a temporary solution for now, hope that helps.

```
repositories {
    mavenCentral()
    maven {
        url 'https://artifacts.camunda.com/artifactory/zeebe-io-snapshots/'
    }
}

dependencies {
    implementation('io.camunda:spring-zeebe-starter:8.1.8') {
        exclude group: 'io.camunda', module: 'zeebe-client-java'
    }
    implementation'io.camunda:zeebe-client-java:8.2.0-SNAPSHOT'
}
```
