### ISSUE TITLE
identity libs not found with version 8.4.2

### ISSUE THREAD

**Issue by NFehringVHV** [camunda-community-hub/spring-zeebe#669] opened 2024-03-11 15:46 UTC
**Describe the bug**

I use maven to load the 8.4.2 version, but the identity libs 
io.camunda:identity-spring-boot-starter:jar:8.4.3
io.camunda:identity-sdk:jar:8.4.3
couldn´t find.

I use a intern artifactory, but this is just a proxy and will normaly find every common lib.

**To Reproduce**
<spring-zeebe.version>8.4.2</spring-zeebe.version>
...
<dependency>
                <groupId>io.camunda</groupId>
                <artifactId>spring-zeebe-starter</artifactId>
                <version>${spring-zeebe.version}</version>
            </dependency>

**Expected behavior**

No exceptions if I load the libs.

**Log/Stacktrace**

[WARNING] Failed to download identity-sdk-8.4.3.pom [https://xxxx/artifactory/libs-release/]
[WARNING] Failed to download identity-sdk-8.4.3.pom [https://xxxx/artifactory/libs-snapshot/]
[WARNING] The POM for io.camunda:identity-sdk:jar:8.4.3 is missing, no dependency information available
[WARNING] Failed to download identity-spring-boot-starter-8.4.3.pom [https://xxxx/artifactory/libs-release/]
[WARNING] Failed to download identity-spring-boot-starter-8.4.3.pom [https://xxxx/artifactory/libs-snapshot/]
[WARNING] The POM for io.camunda:identity-spring-boot-starter:jar:8.4.3 is missing, no dependency information available
[WARNING] The artifact io.camunda:spring-zeebe-starter:jar:8.4.2 has been relocated to io.camunda.spring:spring-boot-starter-camunda:jar:8.4.2
[WARNING] Failed to download identity-spring-boot-starter-8.4.3.jar [https://xxxx/artifactory/libs-release/]
[WARNING] Failed to download identity-spring-boot-starter-8.4.3.jar [https://xxxx/artifactory/libs-snapshot/]
[WARNING] Failed to download identity-sdk-8.4.3.jar [https://xxxx/artifactory/libs-release/]
[WARNING] Failed to download identity-sdk-8.4.3.jar [https://xxxx/artifactory/libs-snapshot/]
Cannot resolve io.camunda:identity-spring-boot-starter:8.4.3
Cannot resolve io.camunda:identity-sdk:8.4.3

**Environment:**
- OS: Windows
- Deployment: -
- Spring-Zeebe Version: 8.4.2
- SpringBoot Version: 3.2.2
- Configuration: -

**Comment by BlackAdam7** [comment] 2024-03-13 07:08
We have same problem.

**Comment by namero999** [comment] 2024-04-09 10:58
Same. Can someone from Camunda take a look at this? Nobody can update to 8.4.2. Is this going to be fixed with 8.5.0?

**Comment by akeller** [comment] 2024-04-09 18:52
This is a community-supported project, and while we do have some Camundi that work in this repo, there is no maintainer(s) at this time.

For the official Camunda-supported version, please refer to the [Zeebe repository](https://github.com/camunda/zeebe). You can also read more about the changes in a [recent blog](https://camunda.com/blog/2024/03/streamlining-camunda-apis-zeebe-rest-api/).

**Comment by namero999** [comment] 2024-04-10 08:02
Thanks. Do you mean this? https://mvnrepository.com/artifact/io.camunda/spring-boot-starter-camunda-sdk/8.5.0

It has the same issue, the identity SDK is not published so it can't be directly used.

**Comment by akeller** [comment] 2024-04-19 15:13
@namero999 can you confirm you are still running into this after following https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/#add-the-spring-zeebe-sdk-to-your-project?

**Comment by namero999** [comment] 2024-04-19 15:53
Thank you for the reply.

I think the question that everybody here is asking, is why is that artifact not published on Maven, together with the other dozens of artifact that Camunda (community or otherwise) already publishes?

For one transitive dependency (which is not even used by most people), developers have now to add a new repository to their project. While not a big deal, it is certainly surprising and time consuming as opposed to a smooth experience as it used to be.

What is preventing the identity sdk to be published to maven?

**Comment by namero999** [comment] 2024-04-24 10:01
Any news on this?

**Comment by namero999** [comment] 2024-04-24 10:08
Also, I can confirm that the issue is still present when using the custom maven repository @akeller 

```
Could not find io.camunda:identity-sdk:8.5.0.
Required by:
    project :CamundaWorkerDemo > io.camunda:spring-boot-starter-camunda-sdk:8.5.0
```

**Comment by akeller** [comment] 2024-04-24 13:16
Hi @namero999, this SDK is not part of my team, so I'm having discussions internally with no public facing issues I can reference.

Currently, the Identity team uploads their artifacts only to Camunda Artifactory. This is in progress on their backlog, but I can't give an estimate. I can tell you that this includes uploading the SDK and starter to Maven central.

**Comment by namero999** [comment] 2024-04-24 13:20
Fantastic this is great to hear, thank you!

**Closed** 2024-05-06 07:46 UTC
