### ISSUE TITLE
Problem with the `ZeebeClient` at the Spring Context initialization phase

### ISSUE THREAD

**Issue by aivinog1** [camunda-community-hub/spring-zeebe#313] opened 2023-01-12 06:37 UTC
I'm creating a Spring Boot starter for the coworker project and I've decided that it should depend on Spring Zeebe.
I've such configuration class:

```kotlin
@Configuration
@AutoConfigureAfter(ZeebeClientStarterAutoConfiguration::class, ZeebeClientSpringConfiguration::class)
@ConditionalOnClass(ZeebeClientStarterAutoConfiguration::class, ZeebeClient::class, ZeebeClientSpringConfiguration::class)
open class CoworkerAutoConfiguration {

    @Bean
    open fun coZeebe(zeebeClient: ZeebeClient): Cozeebe {
        return zeebeClient.toCozeebe()
    }
}
```

The `ZeebeClient#toCozeebe` method looks like this:

```kotlin
fun ZeebeClient.toCozeebe() = CozeebeImpl(this. configuration)
```

So, I have to have ZeebeClient with configuration on the Spring Context Initialization phase. It means that the `ZeebeClientProxy` must have a ZeebeClient instance in the context initialization phase.

I think that my case isn't an exception, this applies to all users that doing something with `ZeebeClient` in the context initialization phase (deploying resources, starting instances, lookup for topology, etc.).

**Comment by berndruecker** [comment] 2023-01-12 07:55
Hey @aivinog1, this is indeed a known limitation at the moment. This can already hurt you if you try to do things in a `@PostConstruct` method. 

Maybe the whole lifecycle of the ZeebeClient could be improved when looking at https://github.com/camunda-community-hub/spring-zeebe/issues/275 - as I am not sure if it really has to be the way it is now, but I also think it is not an easy fix to change...

If you have concrete thoughts how to improve the situation - happy to hear them :-)

**Comment by aivinog1** [comment] 2023-01-15 08:41
Hey @berndruecker!
I have thought about it. My solution is pretty dirty and complicates the logic, but as I can see in my smoke tests, it works. I will create PR with my vision soon :) I need some time to polish it :)

**Comment by berndruecker** [comment] 2023-01-16 13:58
Maybe you can also share the dirty version as a facilitator for discussion @aivinog1?

**Comment by aivinog1** [comment] 2023-01-17 07:20
Sure, @berndruecker! Take a look at https://github.com/aivinog1/spring-zeebe/commit/25f6cbc33fd5a3c5ae1fe282edb47089fe96e8d7

**Comment by berndruecker** [comment] 2023-02-08 08:25
@aivinog1 I had a look and asked one question if I understood the lifecycle correctly: "you now initialize the proxy immediately when creating beans - and then in the first test method nothing happens. In the following test methods, the engine is swapped. Engine creation is then not done in the before/after methods directly, but by the callback handed in - so you can control here when it is created. Is that a correct description of your idea?"

One thing that I wonder: In your use case - when you get a ZeebeClient, how do you cope with the situation that for a new test method the engine gets swapped and thus you need a new ZeebeClient to work properly? Why don't you work with the ZeebeClientProxy instead - which then internally has the right reference automatisally? 

My comment above was more around the overall lifecycle, as the ZeebeClient get's created very late. But for tests where you swap the engine per test method - I am not sure if what you plan works. Or do I oversee something?

**Comment by aivinog1** [comment] 2023-02-09 08:10
> One thing that I wonder: In your use case - when you get a ZeebeClient, how do you cope with the situation that for a new test method the engine gets swapped and thus you need a new ZeebeClient to work properly? Why don't you work with the ZeebeClientProxy instead - which then internally has the right reference automatisally?

When I autowire `ZeebeClient` I already autowire the proxy class (see the `io.camunda.zeebe.spring.test.proxy.TestProxyConfiguration#proxiedZeebeClient`) so every call to the autowired `ZeebeClient` bean goes to the proxy and then to the `ZeebeClient` in it. And between test methods, there is swapping `ZeebeClient` inside the proxy.

**Comment by aivinog1** [comment] 2023-02-09 11:37
@berndruecker Oh, I see the full picture now.

If we even do this with tests, how can I use the `ZeebeClient` bean in my configuration, when I start the app?
Yes, I see the problem here, it requires rewriting the whole lifecycle logic of `ZeebeClient`, i.e. `ZeebeClientLifecycle`

**Comment by berndruecker** [comment] 2023-03-02 09:23
Hey @aivinog1 - sorry for the delay - maybe you can have a look at https://github.com/camunda-community-hub/spring-zeebe/pull/353 - I cleaned up the lifecycle and use normal AutoConfiguration - and I also adjusted how this is handled in tests a little bit. Maybe this helps?

**Comment by berndruecker** [comment] 2023-03-08 08:31
I think this should be addressed by https://github.com/camunda-community-hub/spring-zeebe/pull/363 - let me know if there are any further problems!

**Closed by berndruecker** 2023-03-08 08:31 UTC

**Comment by shahamit** [comment] 2023-10-11 13:11
> Hey @aivinog1, this is indeed a known limitation at the moment. This can already hurt you if you try to do things in a `@PostConstruct` method.

Strange, we are facing this problem. Since the ZeebeClientProxy gets initialised in the before test method, we are not able to use ZeebeClient in the `@PostConstruct` method. Our test case fails to start up. We get an error 

```
Caused by: java.lang.RuntimeException: Cannot invoke public abstract 
io.camunda.zeebe.client.api.worker.JobWorkerBuilderStep1 io.camunda.zeebe.client.ZeebeClient.newWorker() on 
ZeebeClient, as ZeebeClient is currently not initialized. Maybe you run outside of a testcase?
```
Our test class is annotated with `@ZeebeSpringTest`
From the above comments I understand that the lifecycle is fixed but it doesn't seem so. 

What could be still going wrong @berndruecker ?

**Comment by berndruecker** [comment] 2023-10-11 13:54
Hi @shahamit - could you please share the exact version you are experiencing this problem with?
Could you maybe share a small sample problem to reproduce? Maybe you could raise this as a new issue?

**Comment by shahamit** [comment] 2023-10-12 14:03
@berndruecker - I am using spring-zeebe 8.2.3. The problem is pretty straightforward and the same that you explained [above](https://github.com/camunda-community-hub/spring-zeebe/issues/313#issuecomment-1379937729).

If we define a new class that calls any of the methods of `ZeebeClient` in `@PostConstruct` the test cases fail because `ZeebeClientProxy` initialises the delegate `zeebeClient` within it in the `@BeforeTest` method which is done after `@PostConstruct`. Hence the test case fails in the start up phase.

I didn't create a new issue because i thought its the same that this bug talks about. Should I create a new one?

**Comment by namero999** [comment] 2024-08-09 09:45
Hello, has there been any progress on this topic? Even with 8.5.9 it's not possible to use ZeebeClient in test classes in any initialization phase, and we have to replicate some init code (deploying subprocesses etc) in each actual @Test method. 

Any best practice to follow?

**Comment by crocie** [comment] 2025-02-04 12:00
Hello! I also have the same error and I'm using the version 8.6.7 of "spring-boot-starter-camunda-test-testcontainer".

The error is: 

"Cannot invoke public abstract io.camunda.zeebe.client.api.worker.JobWorkerBuilderStep1 io.camunda.zeebe.client.ZeebeClient.newWorker() on ZeebeClient, as ZeebeClient is currently not initialized. Maybe you run outside of a testcase?"

My implementation is:

`@Component
public class DummyServiceWorker {

  private final ZeebeClient zeebeClient;

  public DummyServiceWorker(ZeebeClient zeebeClient) {
    this.zeebeClient = zeebeClient;
  }

  @PostConstruct
  public void registryWorker() {
    zeebeClient
      .newWorker()
      .jobType("dummy_service")
      .handler(new JobHandler() {
        @Override
        public void handle(JobClient client, ActivatedJob job) throws Exception {
          log.info("Execution of {}",job.getType().toLowerCase());
          Map<String, Object> map = new HashMap<>();
          map.put("var1", "Test set variable from job handler");
          client.newCompleteCommand(job.getKey()).variables(map).send().join();
        }
      })
      .tenantIds(List.of("dummy"))
      .timeout(Duration.ofSeconds(10))
      .open();
  }`

Thank you for help!
