### ISSUE TITLE
Use @Variable in another Java variable

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/spring-zeebe#442] opened 2023-06-09 10:11 UTC
Right now, The `@Variable` looks for process variable with the same name as the Java variable name.

As a programmer, I want to use another variable name in my code.

For example: `myHandler(ActivatedJob job, JobClient client, @Variable(name="myVeryLongVaribaleName") String shortName)`.

Just add an optional `name` parameter to the annotation to fetch the process variable for this value.

**Comment by lzgabel** [comment] 2023-06-09 11:40
duplicate of #218 ?

**Comment by ingorichtsmeier** [comment] 2023-06-09 14:58
Oh yes, it is a duplicate. 

But let's keep it open and hear if the experts have changed their minds.

**Comment by namero999** [comment] 2023-06-09 16:06
+1 by virtue of the fact that we can't use reserved java keywords as variable names, but if who writes the BPMN is not aware of that and choses one of those keyword, I don't know how this is supposed to work.

**Comment by NF10** [comment] 2023-06-26 09:47
+1 We use java constants for our process variable names. So with this solution I can use the constants in the Annotation 👍

**Closed** 2023-10-13 14:18 UTC
Labels: enhancement
